format_version: 4
common:
  plan_job: &plan_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
  common_stages: &common_stages
    - promote_docker_image:
        resources:
          - docker
        clean_workspace: true
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks promote_docker_image
    - plan:
        clean_workspace: true
        jobs:
          deploy: *plan_job
    - deploy:
        clean_workspace: true
        jobs:
          deploy: *deploy_job
  prod_stages: &prod_stages
    - promote_docker_image:
        resources:
          - docker
        clean_workspace: true
        tasks:
          - exec:
              command: /bin/bash
              arguments:
                - -c
                - ./tasks promote_docker_image
    - plan:
        clean_workspace: true
        jobs:
          deploy: *plan_job
    - deploy:
        approval:
          type: manual
          allow_only_on_success: true
        clean_workspace: true
        jobs:
          deploy: *deploy_job
pipelines:
  'prm-deductions-pds-adaptor.dev':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-pds-adaptor
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages: *common_stages

  'prm-deductions-pds-adaptor.test':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-pds-adaptor
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
      dev_env:
        pipeline: prm-deductions-pds-adaptor.dev
        stage: deploy
      e2e:
        pipeline: continuity-e2e-tests.dev
        stage: test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages: *common_stages

  'prm-deductions-pds-adaptor.pre-prod':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-pds-adaptor
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
      test_env:
        pipeline: prm-deductions-pds-adaptor.test
        stage: deploy
      e2e:
        pipeline: continuity-e2e-tests.test
        stage: test
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages: *common_stages

  'prm-deductions-pds-adaptor.prod':
    group: continuity-service
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-pds-adaptor
        stage: docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_prod
      test_env:
        pipeline: prm-deductions-pds-adaptor.pre-prod
        stage: deploy
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages: *prod_stages