format_version: 4
pipelines:
  pds-adaptor:
    group: linear-spike
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
        ignore:
          - src/performance/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            test:
              tasks:
                - exec:
                    command: sleep
                    arguments:
                      - 10
      - docker:
          clean_workspace: true
          jobs:
            build:
              tasks:
                - exec:
                    command: sleep
                    arguments:
                      - 10
      - prepare.dev:
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 5
      - deploy.dev:
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 20
      - prepare.test:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 5
      - deploy.test:
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 20
      - prepare.pre-prod:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 5
      - deploy.pre-prod:
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 20
      - prepare.prod:
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 5
      - deploy.prod:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          tasks:
            - exec:
                command: sleep
                arguments:
                  - 20
