format_version: 4
pipelines:
  'prm-deductions-pds-adaptor':
    group: repo-history
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        ignore:
          - src/performance/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            test_unit:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tabs:
                TestReport: build/reports/tests/test/index.html
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_unit
            test_integration:
              resources:
                - docker
              artifacts:
                - build:
                    source: build/reports/tests
              tabs:
                TestReport: tests/integration/index.html
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_integration
            test_coverage:
              artifacts:
                - build:
                    source: build/reports/jacoco
                - build:
                    source: build/reports/tests
              tabs:
                TestReport: tests/test/index.html
                Coverage: jacoco/test/html/index.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_coverage
            code_quality:
              artifacts:
                - build:
                    source: build/reports/spotbugs
              tabs:
                MainSpotbugs: spotbugs/main/spotbugs.html
                IntTSpotbugs: spotbugs/integration/spotbugs.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks code_quality
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: test_unit
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
