format_version: 4

common:
  pipeline-template: &pipeline-template
    group: performance
    label_template: '${COUNT}-${git[:8]}'
    materials:
      git:
        type: configrepo
    stages:
      - performance:
          clean_workspace: true
          approval: manual
          jobs:
            performance_test:
              artifacts:
                - build:
                    source: build/test-results/performance/
                - build:
                    source: build/reports/performance/
              tabs:
                performance: build/reports/performance/report.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance

pipelines:
  pds-adaptor-perf-dev:
    <<: *pipeline-template
    timer:
      spec: 0 0 22 ? * MON,TUE,WED,THU,FRI *
    environment_variables:
      NHS_ENVIRONMENT: dev
      RUN_TIME: 30s
      USERS: 10
      MIN_WAIT_SECONDS: 4
      MAX_WAIT_SECONDS: 5
  pds-adaptor-perf-test:
    <<: *pipeline-template
    timer:
      spec: 0 0 23 ? * MON,TUE,WED,THU,FRI *
    environment_variables:
      NHS_ENVIRONMENT: test
      RUN_TIME: 60s
      USERS: 10
      MIN_WAIT_SECONDS: 4
      MAX_WAIT_SECONDS: 5
  pds-adaptor-perf-pre-prod:
    <<: *pipeline-template
    timer:
      spec: 0 0 0 ? * MON,TUE,WED,THU,FRI *
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
      RUN_TIME: 60s
      USERS: 10
      MIN_WAIT_SECONDS: 4
      MAX_WAIT_SECONDS: 5
