format_version: 4
pipelines:
  'prm-deductions-pds-adaptor.performance-test-env':
    group: performance
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
    timer:
      spec: 0 0 23 ? * MON,TUE,WED,THU,FRI *
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - performance:
          clean_workspace: true
          approval: manual
          jobs:
            performance_test:
              artifacts:
                - build:
                    source: build/test-results/performance/
                    destination: perf-data
                - build:
                    source: build/reports/performance/
                    destination: perf-report
              tabs:
                performance: perf-report/report.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance
