#!/usr/bin/env bash

virtualenv virtualenv_performance
source virtualenv_performance/bin/activate

pip install -r ./src/performance/requirements.txt

locust --locustfile="./src/performance/test_performance.py" \
    --users=2 \
    --spawn-rate=2 \
    --csv="./src/performance/results/report" \
    --html="./src/performance/results/report.html" \
    --headless \
    --run-time=30s \
    --host="https://pds-adaptor.dev.non-prod.patient-deductions.nhs.uk"

deactivate